#### Importação das bibliotecas e funções

In [7]:
import sys
sys.path.append('../')

#Importar modulo de leitura
import src.data_loader.read_data as rd
from src.data_cleaning.dados_ausentes import analisa_dados_ausentes

#### Carrega dados

In [8]:
#Dados de região
df_regiao = rd.read_csv(caminho_arquivo="../data/raw/estado_regiao/estado_regiao.csv", 
                    separador_arquivo=";",
                    encoding="latin-1")

#Dados de pacientes
df_pacientes = rd.read_csv(caminho_arquivo="../data/raw/dados_pacientes/dados_pacientes.csv", 
                    separador_arquivo=";"
                   )

#Dados clinicos
df_clinicos = rd.read_csv(caminho_arquivo="../data/raw/dados_clinicos/dados_clinicos.csv", 
                    separador_arquivo=";"
                   )

Lendo o arquivo ../data/raw/estado_regiao/estado_regiao.csv
Lendo o arquivo ../data/raw/dados_pacientes/dados_pacientes.csv
Lendo o arquivo ../data/raw/dados_clinicos/dados_clinicos.csv

### Analisa dados ausentes a partir da função criada

In [9]:
analisa_dados_ausentes(dataframe=df_pacientes)

            Coluna  Qtde_ausentes Percentual
2  classe_trabalho            387      4.84%
7      qtde_filhos             10      0.13%

In [10]:
analisa_dados_ausentes(dataframe=df_clinicos)

  Coluna  Qtde_ausentes Percentual
1   peso              5      0.85%

In [11]:
analisa_dados_ausentes(dataframe=df_regiao)

Empty DataFrame
Columns: [Coluna, Qtde_ausentes, Percentual]
Index: []

#### Join entre dois dataframes

In [20]:
#Dataframe da esquerda
df_pacientes.head()

,id_cliente,idade,classe_trabalho,escolaridade,id_estado,estado_civil,raca,qtde_filhos,salario
0,1,39,Servidor Público,Ensino Médio Completo,2,Solteiro,Branco,2.0,4754
1,2,50,Autônomo,Superior Incompleto,24,Casado,Branco,1.0,3923
2,3,38,Funcionário Setor Privado,Ensino Médio Incompleto,4,Divorciado,Branco,0.0,1100
3,4,53,Funcionário Setor Privado,Ensino Médio Incompleto,24,Casado,Negro,1.0,1100
4,5,28,Funcionário Setor Privado,Ensino Médio Completo,15,Casado,Negro,0.0,3430

In [19]:
#Dataframe esquerda
df_regiao.head()

   id_estado sigla    estado    regiao    pais
0          1    AC      Acre     Norte  Brasil
1          2    AL   Alagoas  Nordeste  Brasil
2          3    AP     Amapá     Norte  Brasil
3          4    AM  Amazonas     Norte  Brasil
4          5    BA     Bahia  Nordeste  Brasil

In [ ]:
#Join entre as tabelas 

import pandas as pd
pd.merge(left = df_pacientes,
         right = df_regiao,
         how = 'inner',
         on = "id_estado"
         )


#No caso acima o relacionamento foi feito pelo ID do estado, a coluna existe nas duas tabelas. 
#Caso fosse outro atributo, adicona a clausula left_on e right_on:
#pd.merge(left = df_pacientes,
#         right = df_regiao,
#         how = 'inner',
#         left_on = "id_estado",
#         right_on = "id_estado" (ou cod_estado com o exemplo abaixo)
#         )

#Caso queira testar, a coluna pode ser renomeada para "cod_estado" por exemplo e ajustada a consulta acima
#df_regiao.rename(columns={"id_estado":"cod_estado"}, inplace=True)
#ou renomeia direto na tabela, mas é algo que se for repetitivo precisará ser refeito diversas vezes

,id_cliente,idade,classe_trabalho,escolaridade,id_estado,estado_civil,raca,qtde_filhos,salario,sigla,estado,regiao,pais
0,1,39,Servidor Público,Ensino Médio Completo,2,Solteiro,Branco,2.0,4754,AL,Alagoas,Nordeste,Brasil
1,2,50,Autônomo,Superior Incompleto,24,Casado,Branco,1.0,3923,SC,Santa Catarina,Sul,Brasil
2,3,38,Funcionário Setor Privado,Ensino Médio Incompleto,4,Divorciado,Branco,0.0,1100,AM,Amazonas,Norte,Brasil
3,4,53,Funcionário Setor Privado,Ensino Médio Incompleto,24,Casado,Negro,1.0,1100,SC,Santa Catarina,Sul,Brasil
4,5,28,Funcionário Setor Privado,Ensino Médio Completo,15,Casado,Negro,0.0,3430,PB,Paraíba,Nordeste,Brasil
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,7995,23,Funcionário Setor Privado,Ensino Médio Completo,7,Casado,Negro,3.0,2856,DF,Distrito Federal,Centro-Oeste,Brasil
7995,7996,19,Funcionário Setor Privado,Ensino Médio Incompleto,5,Solteiro,Branco,1.0,1100,BA,Bahia,Nordeste,Brasil
7996,7997,44,NaN,Ensino Médio Completo,23,Casado,Branco,0.0,3729,RR,Roraima,Norte,Brasil
7997,7998,20,Funcionário Setor Privado,Ensino Médio Incompleto,8,Solteiro,Negro,0.0,1100,ES,Espírito Santo,Sudeste,Brasil
7998,7999,41,Funcionário Setor Privado,Ensino Médio Completo,13,Casado,Branco,1.0,2579,MG,Minas Gerais,Sudeste,Brasil